### ISSUE TITLE
CI green for https://github.com/pawelru/ie_status?tab=readme-ov-file

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/nestcolor#71]
# todo

- [x] dependencies test min_cohort https://github.com/insightsengineering/nestcolor/actions/runs/10437597835/job/28903955974
- [x] dependencies test_isolated https://github.com/insightsengineering/nestcolor/actions/runs/10437597835/job/28903956228
- [x] nosuggests https://github.com/insightsengineering/nestcolor/actions/runs/10437597835/job/28903958671
